### ISSUE TITLE
Method naming guidelines

### ISSUE THREAD

**Issue by rlightner** [workos/workos-dotnet#91]
What coding conventions is being followed for naming? Notice that the async methods are not suffixed with Async.

cite:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model#BKMK_NamingConvention

**Comment by maxdeviant** [comment]
At the moment we aren't following any specific naming convention for the .NET SDK outside of our internal coding guidelines.

The choice to omit the `Async` suffix was done to reduce noise, as the majority of the operations exposed by the SDK (all of the ones that need to communicate with the WorkOS API) are asynchronous and will never have synchronous variants.

Here's an example of another library that also chooses not to use the `Async` suffix, along with their rationale: [NServiceBus - No Async Suffix](https://docs.particular.net/nservicebus/upgrades/5to6/async-suffix)
